---
title: "Temperature Dashboard"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(shiny)
library(DT)
library(dplyr)
source("scratch.R")

weather_data <- getWeatherData()
```

Column {.sidebar}
-----------------------------------------------------------------------

Select Station ID and Date Range

```{r}
selectInput(inputId = "station",
            label = h4("Station"),
            choices = unique(weather_data$stationID),
            selected = "KWASEATT2743"
)
dateRangeInput(inputId = "dates", 
               label = h4("Date range"),
               start = min(weather_data$obsTimeUtc),
               end = max(weather_data$obsTimeUtc)
)

# Reactive data
station_data <- reactive({
  weather_data[weather_data$stationID == input$station,]
})

temp_data <- reactive({
  getVariableData(station_data(), vars = "imperial.temp")
})

daily_min_max_temps <- reactive({
  getDailyTemps(df = temp_data()) %>% 
    filter(date >= input$dates[1] & 
             date <= input$dates[2])
})
```

Column
-----------------------------------------------------------------------

### Last 8 Hours

```{r}

renderDT(rownames = FALSE,
         server = FALSE,
         options = list(bPaginate = FALSE, 
                        dom = 't',
                        ordering=F), 
         { temp_data() %>% 
             tail(n = 8) %>%
             arrange(desc(obsTimeLocal)) %>%
             mutate(obsTimeLocal = as.character(obsTimeLocal)
             )
         })
```

### Daily Min and Max Temperatures

```{r}

renderDT(rownames = FALSE,
         server = FALSE,
         options = list(bPaginate = FALSE, 
                        dom = 't',
                        ordering=F,
                        scrollY = "350px"), 
         {daily_min_max_temps() %>% arrange(desc(date))
         })
# foo
```

